export type Member = {
  id: number;
  name: string;
  role: "super_admin" | "admin" | "member";
  color: string;
  avatarMediaKey: string | null;
  faceReferenceMediaKey: string | null;
  faceRecognitionConsent: boolean;
  isGuest: boolean;
  guestMeetingId: number | null;
};
export type Book = { id: number; title: string; author: string; publisher: string | null; pages: number | null; isbn: string | null; coverUrl: string | null; sourceUrl: string | null };
export type Meeting = { id: number; bookId: number; date: string; location: string; mapUrl: string | null; note: string | null; readingScope: string | null; bookStatus: "continuing" | "completed"; createdBy: number; createdAt: string; deletedAt: string | null };
export type Attendance = { meetingId: number; memberId: number; readingStatus: "read" | "partial" | "unread" | "unselected"; currentPage: number | null };
export type MeetingRsvp = { meetingId: number; memberId: number; createdAt: string; updatedAt: string };
export type Review = { meetingId: number; memberId: number; rating: number; comment: string | null; updatedAt: string };
export type Photo = { id: number; meetingId: number; mediaKey: string; uploadedBy: number; createdAt: string };
export type Plan = { id: number; bookId: number; plannedDate: string | null; note: string | null; createdBy: number; deletedAt: string | null };
export type Favorite = { memberId: number; bookId: number; createdAt: string };
export type BookVote = { memberId: number; roadmapId: number; createdAt: string };
export type TrashItem = { type: "meeting" | "plan"; id: number; bookId: number; deletedAt: string; date: string | null };
export type AppData = { currentMemberId?: number; members: Member[]; books: Book[]; meetings: Meeting[]; attendance: Attendance[]; meetingRsvps: MeetingRsvp[]; reviews: Review[]; photos: Photo[]; roadmap: Plan[]; favorites: Favorite[]; bookVotes: BookVote[]; voteVisibility: "open" | "secret"; trash: TrashItem[]; clubFeaturesReady: boolean; rsvpFeaturesReady: boolean };
export const readingLabels: Record<Attendance["readingStatus"], string> = { read: "Okudum", partial: "Kısmen okudum", unread: "Okumadım", unselected: "Henüz belirtmedi" };
export const isAdminRole = (role: Member["role"]) => role === "super_admin" || role === "admin";
export const isSuperAdminRole = (role: Member["role"]) => role === "super_admin";
